FROM node:18-alpine

ENV PORT=8080

WORKDIR /app

RUN apk add --no-cache git

RUN git clone https://github.com/Lroq/Hackengine.git

WORKDIR /app/Hackengine

RUN npm install

EXPOSE 8080

CMD ["npm", "start"]
