name: CI/CD Hackemon

on:
  push:
    branches: [ "main", "feat/docker", "feat/CI-CD", "dev" ]
  pull_request:
    branches: [ "main", "feat/docker", "feat/CI-CD", "dev" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Installation des dépendances
        run: npm ci


