name: CI/CD Hackemon

on:
  push:
    branches: [ "main", "feat/docker", "feat/CI-CD", "dev" ]
  pull_request:
    branches: [ "main", "feat/docker", "feat/CI-CD", "dev" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Installation des dépendances
        run: npm ci

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' # Déploiement auto seulement sur les branches cibles

    steps:
      - name: Déploiement sur le serveur via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}     # L'adresse IP de ton VPS Ynov
          username: ${{ secrets.SERVER_USER }} # Le nom d'utilisateur SSH (souvent root, admin, ou ton nom)
          key: ${{ secrets.SERVER_SSH_KEY }}   # La clé privée SSH permettant de s'y connecter
          script: |
            # 1. Mise à jour du code source (dossier www)
            cd /home/hackemon/www
            git pull

            # 2. Construction et redémarrage des conteneurs
            cd /srv/hackemon
            docker-compose up --build -d
